name: deploy cf

# on: push
on:
  push:
    branches:
      - main
jobs:
  deploy-cf:
    runs-on: ubuntu-latest
    steps:
      - run: echo "do pull"
      - run: echo "make migrations"
      - run: echo "bye bye"
