name: deploy CF

# on: push
on: push
#   push:
# branches:
#   - main
jobs:
  deploy-cf:
    runs-on: ubuntu-latest
    env:
      NAME: CF
    steps:
      - run: echo "testing gpo"
      - run: echo "just push"
      - name: incl env dot var_name
        run: echo "Hi Mr. ${{ env.NAME }}"
      - name: only dollar inside comillas
        run: echo "Hi Mr. $NAME"
      - run: echo "bye bye"
