name: deploy CF

# on: push
on: push
#   push:
# branches:
#   - main
jobs:
  deploy-cf:
    runs-on: ubuntu-latest
    env:
      NAME: CF
    steps:
      - run: echo "testing gpo"
      - run: echo "just push"
      - run: echo "Hi Mr. ${{ env.NAME }}"
      - run: echo "bye bye"
